name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Replace with your branch name if it's not 'main'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Raspberry Pi
      run: |
        # Navigate to your project directory on the Pi
        cd /home/Dan/Projects

        # Pull the latest changes
        git pull origin main
